version: '3.8'


services:
  express-api:
    build:
      context: .
    container_name: nutriscan-api-server
    ports:
      - "3000:3000"

    volumes:
      - .:/usr/src/app

    environment:
      NODE_ENV: production
    restart: unless-stopped
