version: '3.8'


services:
  express-api:
    image: node:16
    build:
      context: .
    container_name: nutriscan-api-server
    ports:
      - "3001:3000"
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    environment:
      NODE_ENV: production
    command: | 
      sh -c "npm install && npm start"
    restart: unless-stopped
