name: Deploy Nutriscan Express API


on:
  push:
    branches:
      - master



jobs:
  deploy:
    runs-on: self-hosted


    steps:
      -name: Checkout code
       uses: actions/checkout@v4

      -name: Stop and remove old containers
       run: |
         docker compose down || true

      -name: Create .env file
       run: | 
         echo "DB_USER=${{ secrets.DB_USER}}" >> .env
         echo "DB_NAME=${{ secrets.DB_NAME}}" >> .env
         echo "DB_HOST=${{ secrets.DB_HOST}}" >> .env
         echo "DB_PORT=${{ secrets.DB_PORT}}" >> .env
         echo "DB_PASSWORD=${{ secrets.DB_PASSWORD}}" >> .env
         echo "JWT_SECRET=${{ secrets.JWT_SECRET}}" >> .env

      - name: Start Server
        run: |
          docker compose up -d

